language: python
cache: pip

matrix:
  include:
  - python: 3.6
    env: SOURCE_DIR=lib
  - python: 3.8
    env: SOURCE_DIR=lib

install:
- wget http://www.antlr.org/download/antlr-4.8-complete.jar
- make
- pip install -I -e .
- pip install coveralls

script:
- coverage run --source=$SOURCE_DIR -m pytest $SOURCE_DIR

after_success:
- coveralls
